bind_address = "0.0.0.0"
bind_port = 4242

[apps]
    [apps.MyFirstApp]
    name = "My First App"
    hockeyapp_id = "deadbeefdeadbeefdeadbeefdeadbeef"
    hockeyapp_api_token = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

    [apps.MyFirstApp.crash_handlers]

        [apps.MyFirstApp.crash_handlers.fogbugz]
        type = "fogbugz"

        [apps.MyFirstApp.crash_handlers.fogbugz.config]
        host = "mycompany.fogbugz.com"
        email = "me@mycompany.com"
        password = "p@ssword"
        project = "MyFirstApp"
        area = "CrashReports"

    [apps.MySecondApp]
    name = "My Second App"
    hockeyapp_id = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
    hockeyapp_api_token = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

    [apps.MySecondApp.crash_handlers]

        [apps.MySecondApp.crash_handlers.fogbugz]
        type = "fogbugz"

        [apps.MySecondApp.crash_handlers.fogbugz.config]
        host = "mycompany.fogbugz.com"
        email = "me@mycompany.com"
        password = "p@ssword"
        project = "MySecondApp"
        area = "CrashReports"

    [apps.MySecondApp.release_handlers]

        [apps.MySecondApp.release_handlers.email_mymailinglist]
        type = "email"

        [apps.MySecondApp.release_handlers.email_mymailinglist.config]
        smtp_server = "smtp.gmail.com"
        smtp_port = 587
        smtp_username = "no-reply@mycompany.com"
        smtp_password = "p@ssw0rd"

        from = "Hooky App <no-reply@mycompany.com>"
        to = "Mailing List <mymailinglist@mycompany.com>"
        template = "email_template.html"
